server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: az
      password: 123
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
