server:
  port: 8002

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica1
  client:
    fetch-registry: true # only for client
    register-with-eureka: true # only for client
    service-url:
      defaultZone: http://replica2:8003/eureka/
