server:
  port: 8003

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: true # only for client
    register-with-eureka: true # only for client
    service-url:
      defaultZone: http://replica1:8002/eureka/
