server:
  port: 8001

spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # only for client (standalone instance)
    register-with-eureka: false # only for client
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: health, mapping
