server:
  port: 8088

spring:
  application:
    name: little-metrics
  security:
    user:
      name: admin
      password: admin
      roles: [ 'ENDPOINT_ADMIN' ]

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
