spring:
  datasource:
    username: root
    password: azusa520
    url: jdbc:mysql://localhost:3306/azusa?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
