server:
  port: 8101
spring:
  application:
    name: eureka-client

eureka:
  instance:
    hostname: localhost:${server.port}
    statusPageUrl: http://${eureka.hostname}/info
    healthCheckUrl: http://${eureka.hostname}/health
    homePageUrl: http://${eureka.hostname}/
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/, http://localhost/8004/eureka
      # defaultZone: http://replica1:8002/eureka/,http://replica2:8003/eureka/
