server:
    port: 8443

spring:
    application:
        name: LittleAuth
    thymeleaf:
        cache: false
    devtools:
        restart:
            additional-paths: src/main/java
            exclude: static/**, public/**
    redis:
        database: 0
        host: localhost
        port: 6379
        password:

