server:
  port: 8401

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# from config server
user:
  service:
    name: ${provider.service.name}
#
provider:
  service:
    name: user-service-provider
    host: localhost
    port: 8301


# kafka config

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: az-group
      client-id: user-service-client
    producer:
      value-serializer: cn.az.cloud.serializer.ObjectSerializer
  # Spring Cloud Stream Binding config
  # user-message-output -> output pipeline
  cloud:
    stream:
      bindings:
        user-message-out:
          destination: az-users
        activemq-out:
          binder: activemq
          destination: az-users-activemq
  sleuth:
    sampler:
      rate: 10

