server:
  port: 8088

spring:
  application:
    name: little-metrics

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
